services:
  citus-coordinator:
    container_name: z-social-network-citus-coordinator
    image: citusdata/citus:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: z-social-network
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - social-network
    command: ["postgres", "-c", "shared_preload_libraries=citus", "-c", "listen_addresses=*"]

  citus-worker-1:
    container_name: z-social-network-citus-worker-1
    image: citusdata/citus:latest
    ports:
      - "5433:5432"  # Экспортируем порт для отладки
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: z-social-network
    networks:
      - social-network
    command: ["postgres", "-c", "shared_preload_libraries=citus", "-c", "listen_addresses=*"]

  citus-worker-2:
    container_name: z-social-network-citus-worker-2
    image: citusdata/citus:latest
    ports:
      - "5434:5432"  # Экспортируем порт для отладки
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: z-social-network
    networks:
      - social-network
    command: ["postgres", "-c", "shared_preload_libraries=citus", "-c", "listen_addresses=*"]

  z-social-network-hw5:
    container_name: z-social-network-hw5
    image: zsalamandra/z-social-network-hw5
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    restart: unless-stopped
    networks:
      - social-network
    environment:
      - JAVA_OPTS="-Xmx1024m -Xms512m"
    depends_on:
      - citus-coordinator

networks:
  social-network:
    driver: bridge