server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/z-social-network
    username: root
    password: root
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml