version: '3.8'

services:
  tarantool:
    container_name: z-social-network-hw7-tarantool
    image: tarantool/tarantool:2.10.4
    ports:
      - "3301:3301"
    volumes:
      - ./tarantool/init.lua:/opt/tarantool/init.lua
      - ./tarantool/app:/opt/tarantool/app
      - tarantool-data:/var/lib/tarantool
    environment:
      TARANTOOL_USER_NAME: admin
      TARANTOOL_USER_PASSWORD: pass
    command: tarantool /opt/tarantool/init.lua
    networks:
      - social-network

  postgres:
    container_name: z-social-network-hw7-postgres
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: z-social-network
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - social-network

  # Zookeeper для Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: z-social-network-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - social-network

  # Kafka для очередей сообщений
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: z-social-network-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - social-network

  # Redis для кеширования и хранения WebSocket сессий
  redis:
    image: redis:alpine
    container_name: z-social-network-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - social-network


  z-social-network-hw7:
    container_name: z-social-network-hw7-app
    image: zsalamandra/z-social-network-hw7
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
        CONFIG_FILE: application-in-memory.yaml
    ports:
      - "8085:8085"
    restart: unless-stopped
    networks:
      - social-network
    environment:
      - JAVA_OPTS="-Xmx1024m -Xms512m"
      - SPRING_DATASOURCE_MASTER_URL=jdbc:postgresql://z-social-network-hw7-postgres:5432/z-social-network
      - TARANTOOL_HOST=z-social-network-hw7-tarantool
      - TARANTOOL_PORT=3301
      - TARANTOOL_USERNAME=admin
      - TARANTOOL_PASSWORD=pass
      - INITIALIZER_NODE=app
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATA_REDIS_HOST=redis

  jmeter:
    container_name: z-social-network-hw7-jmeter
    build:
      context: jmeter-test
      dockerfile: Dockerfile
    image: zsalamandra/z-social-network-hw7-jmeter
    environment:
      - HOST=z-social-network-hw7-app
      - PORT=8085
    volumes:
      - ./results:/results
    networks:
      - social-network

  # Контейнер для тестирования Tarantool
#  tarantool-test:
#    container_name: z-social-network-hw7-tarantool-test
#    image: zsalamandra/tarantool-test
#    build:
#      context: ./tarantool-test
#      dockerfile: Dockerfile
#    stdin_open: true
#    tty: true
#    networks:
#      - social-network
#    depends_on:
#      - tarantool

networks:
  social-network:
    driver: bridge

volumes:
  postgres-data:
  tarantool-data:
  redis-data: