server:
  port: 8085

logging:
  level:
    com.p6spy.engine: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.transaction.interceptor: DEBUG

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://localhost:5432/z-social-network
    username: root
    password: root

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml