server:
  port: 8085

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.transaction.interceptor: DEBUG

spring:
#  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:postgresql://localhost:5432/z-social-network
#    url: jdbc:postgresql://postgres-master:5432/z-social-network
#    username: root
#    password: root

  datasource:
    master:
      jdbc-url: jdbc:postgresql://localhost:5432/z-social-network
      url: jdbc:postgresql://localhost:5432/z-social-network
      username: root
      password: root
      driver-class-name: org.postgresql.Driver
    slave:
      jdbc-url: jdbc:postgresql://localhost:15432/z-social-network
      url: jdbc:postgresql://localhost:15432/z-social-network
      username: root
      password: root
      driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true


